# config.yaml

# --- Project Settings ---
base_run_name: "SimpleMLP_baseline" # CHANGE THIS EVERY TIME => is the base name for generating unique training runs
output_dir: "runs"                  # Main directory to save all outputs

# --- Dataset Settings ---
data_path: "../dataset"
train_scenes: ["scene1", "scene2"]
val_scenes: ["scene3"]
test_scenes: ["scene4"]

# --- Model Settings ---
input_channels: 13              # 12 Sentinel-2 bands + 1 Aerosol band

# --- Training Settings ---
device: "cuda"                  # "cuda" or "cpu"
batch_size: 16                  # Adjust based on your GPU memory
epochs: 5                       # Increased for a more meaningful training
learning_rate: 0.001
num_workers: 4                  # Adjust based on your CPU cores

# --- Output Settings ---
results_file: "runs/test_results.txt"



# TO TRAIN
# python train.py